# 04 Embedding Baseline

Purpose: embed degree module texts and cleaned job texts, then compute the baseline degree-job similarity matrix.

Inputs:
- `data/processed/degree_modules.parquet`
- `data/processed/degree_profiles.parquet`
- `data/interim/jobs_clean.parquet`

Outputs:
- `data/embeddings/degree_module_embeddings_all-MiniLM-L6-v2.npy`
- `data/embeddings/degree_embeddings_all-MiniLM-L6-v2.npy`
- `data/embeddings/job_embeddings_all-MiniLM-L6-v2.npy`
- `data/embeddings/similarity_matrix_all-MiniLM-L6-v2.npy`
- `data/figures/similarity_distributions.png`

In [1]:
import sys
import warnings
from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from IPython.display import display

warnings.filterwarnings('ignore')
repo_root = Path.cwd().resolve()
if repo_root.name == 'notebooks':
    repo_root = repo_root.parent
if str(repo_root) not in sys.path:
    sys.path.insert(0, str(repo_root))

from analysis.io import paths, require_files

%matplotlib inline
plt.rcParams['figure.figsize'] = (12, 6)
plt.rcParams['font.size'] = 11

from analysis.embedding import build_degree_embeddings, compute_similarity_matrix, load_or_compute_embeddings, top_k_jobs_for_degree
from analysis.plotting import plot_similarity_distributions
from analysis.preprocessing import build_structured_job_text
from analysis.profiles import build_degree_module_indices, build_module_text

MODEL_NAME = 'all-MiniLM-L6-v2'
DEGREE_MODULE_TOP_K = 5

require_files([paths.degree_modules_parquet, paths.degree_profiles_parquet, paths.jobs_clean_parquet])
print('Expected upstream inputs: cleaned jobs and processed degree artifacts')

Expected upstream inputs: cleaned jobs and processed degree artifacts

In [2]:
degree_modules = pd.read_parquet(paths.degree_modules_parquet)
degree_profiles = pd.read_parquet(paths.degree_profiles_parquet)
jobs = pd.read_parquet(paths.jobs_clean_parquet)

if 'module_profile_text' not in degree_modules.columns:
    degree_modules['module_profile_text'] = degree_modules.apply(build_module_text, axis=1)
if 'job_text' not in jobs.columns:
    jobs['job_text'] = jobs.apply(build_structured_job_text, axis=1)

degree_module_indices = build_degree_module_indices(degree_profiles, degree_modules)
module_embeddings = load_or_compute_embeddings(
    degree_modules['module_profile_text'].tolist(),
    paths.degree_module_embeddings_npy(MODEL_NAME),
    model_name=MODEL_NAME,
    batch_size=32,
)

if paths.degree_embeddings_npy(MODEL_NAME).exists():
    degree_embeddings = np.load(paths.degree_embeddings_npy(MODEL_NAME))
    if degree_embeddings.shape[0] != len(degree_profiles):
        degree_embeddings = build_degree_embeddings(degree_profiles, degree_module_indices, module_embeddings)
        np.save(paths.degree_embeddings_npy(MODEL_NAME), degree_embeddings)
else:
    degree_embeddings = build_degree_embeddings(degree_profiles, degree_module_indices, module_embeddings)
    np.save(paths.degree_embeddings_npy(MODEL_NAME), degree_embeddings)

job_embeddings = load_or_compute_embeddings(
    jobs['job_text'].tolist(),
    paths.job_embeddings_npy(MODEL_NAME),
    model_name=MODEL_NAME,
    batch_size=64,
)

if paths.similarity_matrix_npy(MODEL_NAME).exists():
    sim_matrix = np.load(paths.similarity_matrix_npy(MODEL_NAME))
    expected_shape = (len(degree_profiles), len(jobs))
    if sim_matrix.shape != expected_shape:
        sim_matrix = compute_similarity_matrix(degree_profiles, degree_module_indices, module_embeddings, job_embeddings, DEGREE_MODULE_TOP_K)
        np.save(paths.similarity_matrix_npy(MODEL_NAME), sim_matrix)
else:
    sim_matrix = compute_similarity_matrix(degree_profiles, degree_module_indices, module_embeddings, job_embeddings, DEGREE_MODULE_TOP_K)
    np.save(paths.similarity_matrix_npy(MODEL_NAME), sim_matrix)

print(f'Module embeddings shape: {module_embeddings.shape}')
print(f'Degree embeddings shape: {degree_embeddings.shape}')
print(f'Job embeddings shape: {job_embeddings.shape}')
print(f'Similarity matrix shape: {sim_matrix.shape}')

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

Loading weights: 100%|██████████| 103/103 [00:00<00:00, 11733.75it/s]

BertModel LOAD REPORT from: sentence-transformers/all-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Batches:   0%|          | 0/4 [00:00<?, ?it/s]

Batches:  25%|██▌       | 1/4 [00:00<00:01,  2.53it/s]

Batches:  50%|█████     | 2/4 [00:00<00:00,  3.36it/s]

Batches:  75%|███████▌  | 3/4 [00:00<00:00,  3.91it/s]

Batches: 100%|██████████| 4/4 [00:00<00:00,  4.36it/s]

Batches:   0%|          | 0/272 [00:00<?, ?it/s]

Batches:   0%|          | 1/272 [00:00<02:23,  1.89it/s]

Batches:   1%|          | 2/272 [00:01<02:16,  1.98it/s]

Batches:   1%|          | 3/272 [00:01<02:11,  2.04it/s]

Batches:   1%|▏         | 4/272 [00:01<02:10,  2.06it/s]

Batches:   2%|▏         | 5/272 [00:02<02:09,  2.06it/s]

Batches:   2%|▏         | 6/272 [00:02<02:10,  2.04it/s]

Batches:   3%|▎         | 7/272 [00:03<02:09,  2.04it/s]

Batches:   3%|▎         | 8/272 [00:03<02:09,  2.04it/s]

Batches:   3%|▎         | 9/272 [00:04<02:08,  2.04it/s]

Batches:   4%|▎         | 10/272 [00:04<02:08,  2.04it/s]

Batches:   4%|▍         | 11/272 [00:05<02:08,  2.03it/s]

Batches:   4%|▍         | 12/272 [00:05<02:09,  2.01it/s]

Batches:   5%|▍         | 13/272 [00:06<02:08,  2.01it/s]

Batches:   5%|▌         | 14/272 [00:06<02:08,  2.01it/s]

Batches:   6%|▌         | 15/272 [00:07<02:16,  1.88it/s]

Batches:   6%|▌         | 16/272 [00:08<02:20,  1.82it/s]

Batches:   6%|▋         | 17/272 [00:08<02:18,  1.84it/s]

Batches:   7%|▋         | 18/272 [00:09<02:14,  1.88it/s]

Batches:   7%|▋         | 19/272 [00:09<02:11,  1.92it/s]

Batches:   7%|▋         | 20/272 [00:10<02:10,  1.93it/s]

Batches:   8%|▊         | 21/272 [00:10<02:08,  1.96it/s]

Batches:   8%|▊         | 22/272 [00:11<02:06,  1.97it/s]

Batches:   8%|▊         | 23/272 [00:11<02:08,  1.94it/s]

Batches:   9%|▉         | 24/272 [00:12<02:07,  1.95it/s]

Batches:   9%|▉         | 25/272 [00:12<02:05,  1.97it/s]

Batches:  10%|▉         | 26/272 [00:13<02:04,  1.98it/s]

Batches:  10%|▉         | 27/272 [00:13<02:03,  1.99it/s]

Batches:  10%|█         | 28/272 [00:14<02:02,  1.99it/s]

Batches:  11%|█         | 29/272 [00:14<02:01,  2.00it/s]

Batches:  11%|█         | 30/272 [00:15<02:01,  1.99it/s]

Batches:  11%|█▏        | 31/272 [00:15<02:01,  1.99it/s]

Batches:  12%|█▏        | 32/272 [00:16<02:01,  1.98it/s]

Batches:  12%|█▏        | 33/272 [00:16<02:01,  1.96it/s]

Batches:  12%|█▎        | 34/272 [00:17<02:00,  1.97it/s]

Batches:  13%|█▎        | 35/272 [00:17<02:00,  1.97it/s]

Batches:  13%|█▎        | 36/272 [00:18<02:03,  1.92it/s]

Batches:  14%|█▎        | 37/272 [00:18<02:00,  1.94it/s]

Batches:  14%|█▍        | 38/272 [00:19<01:59,  1.96it/s]

Batches:  14%|█▍        | 39/272 [00:19<01:58,  1.96it/s]

Batches:  15%|█▍        | 40/272 [00:20<01:58,  1.96it/s]

Batches:  15%|█▌        | 41/272 [00:20<01:56,  1.98it/s]

Batches:  15%|█▌        | 42/272 [00:21<01:56,  1.98it/s]

Batches:  16%|█▌        | 43/272 [00:21<01:55,  1.98it/s]

Batches:  16%|█▌        | 44/272 [00:22<01:54,  1.99it/s]

Batches:  17%|█▋        | 45/272 [00:22<01:54,  1.98it/s]

Batches:  17%|█▋        | 46/272 [00:23<01:53,  1.99it/s]

Batches:  17%|█▋        | 47/272 [00:23<01:53,  1.98it/s]

Batches:  18%|█▊        | 48/272 [00:24<01:52,  1.99it/s]

Batches:  18%|█▊        | 49/272 [00:24<01:52,  1.98it/s]

Batches:  18%|█▊        | 50/272 [00:25<01:51,  1.99it/s]

Batches:  19%|█▉        | 51/272 [00:25<01:51,  1.98it/s]

Batches:  19%|█▉        | 52/272 [00:26<01:50,  1.99it/s]

Batches:  19%|█▉        | 53/272 [00:26<01:50,  1.98it/s]

Batches:  20%|█▉        | 54/272 [00:27<01:50,  1.98it/s]

Batches:  20%|██        | 55/272 [00:27<01:49,  1.98it/s]

Batches:  21%|██        | 56/272 [00:28<01:48,  1.98it/s]

Batches:  21%|██        | 57/272 [00:28<01:51,  1.93it/s]

Batches:  21%|██▏       | 58/272 [00:29<01:50,  1.94it/s]

Batches:  22%|██▏       | 59/272 [00:29<01:48,  1.96it/s]

Batches:  22%|██▏       | 60/272 [00:30<01:47,  1.98it/s]

Batches:  22%|██▏       | 61/272 [00:30<01:46,  1.98it/s]

Batches:  23%|██▎       | 62/272 [00:31<01:45,  1.98it/s]

Batches:  23%|██▎       | 63/272 [00:31<01:46,  1.97it/s]

Batches:  24%|██▎       | 64/272 [00:32<01:45,  1.96it/s]

Batches:  24%|██▍       | 65/272 [00:32<01:44,  1.98it/s]

Batches:  24%|██▍       | 66/272 [00:33<01:43,  1.98it/s]

Batches:  25%|██▍       | 67/272 [00:33<01:43,  1.98it/s]

Batches:  25%|██▌       | 68/272 [00:34<01:42,  1.99it/s]

Batches:  25%|██▌       | 69/272 [00:34<01:42,  1.99it/s]

Batches:  26%|██▌       | 70/272 [00:35<01:41,  1.98it/s]

Batches:  26%|██▌       | 71/272 [00:35<01:41,  1.99it/s]

Batches:  26%|██▋       | 72/272 [00:36<01:40,  1.98it/s]

Batches:  27%|██▋       | 73/272 [00:36<01:40,  1.98it/s]

Batches:  27%|██▋       | 74/272 [00:37<01:39,  1.99it/s]

Batches:  28%|██▊       | 75/272 [00:38<01:42,  1.92it/s]

Batches:  28%|██▊       | 76/272 [00:38<01:41,  1.94it/s]

Batches:  28%|██▊       | 77/272 [00:39<01:41,  1.93it/s]

Batches:  29%|██▊       | 78/272 [00:39<01:42,  1.89it/s]

Batches:  29%|██▉       | 79/272 [00:40<01:43,  1.86it/s]

Batches:  29%|██▉       | 80/272 [00:40<01:42,  1.88it/s]

Batches:  30%|██▉       | 81/272 [00:41<01:42,  1.87it/s]

Batches:  30%|███       | 82/272 [00:41<01:40,  1.89it/s]

Batches:  31%|███       | 83/272 [00:42<01:38,  1.91it/s]

Batches:  31%|███       | 84/272 [00:42<01:36,  1.94it/s]

Batches:  31%|███▏      | 85/272 [00:43<01:38,  1.89it/s]

Batches:  32%|███▏      | 86/272 [00:43<01:36,  1.92it/s]

Batches:  32%|███▏      | 87/272 [00:44<01:35,  1.94it/s]

Batches:  32%|███▏      | 88/272 [00:44<01:34,  1.96it/s]

Batches:  33%|███▎      | 89/272 [00:45<01:32,  1.97it/s]

Batches:  33%|███▎      | 90/272 [00:45<01:32,  1.97it/s]

Batches:  33%|███▎      | 91/272 [00:46<01:31,  1.98it/s]

Batches:  34%|███▍      | 92/272 [00:46<01:32,  1.95it/s]

Batches:  34%|███▍      | 93/272 [00:47<01:32,  1.93it/s]

Batches:  35%|███▍      | 94/272 [00:47<01:31,  1.95it/s]

Batches:  35%|███▍      | 95/272 [00:48<01:30,  1.95it/s]

Batches:  35%|███▌      | 96/272 [00:48<01:30,  1.95it/s]

Batches:  36%|███▌      | 97/272 [00:49<01:29,  1.96it/s]

Batches:  36%|███▌      | 98/272 [00:49<01:29,  1.94it/s]

Batches:  36%|███▋      | 99/272 [00:50<01:30,  1.91it/s]

Batches:  37%|███▋      | 100/272 [00:51<01:30,  1.89it/s]

Batches:  37%|███▋      | 101/272 [00:51<01:29,  1.92it/s]

Batches:  38%|███▊      | 102/272 [00:52<01:27,  1.94it/s]

Batches:  38%|███▊      | 103/272 [00:52<01:26,  1.95it/s]

Batches:  38%|███▊      | 104/272 [00:53<01:25,  1.96it/s]

Batches:  39%|███▊      | 105/272 [00:53<01:24,  1.98it/s]

Batches:  39%|███▉      | 106/272 [00:54<01:23,  1.99it/s]

Batches:  39%|███▉      | 107/272 [00:54<01:23,  1.99it/s]

Batches:  40%|███▉      | 108/272 [00:55<01:22,  1.99it/s]

Batches:  40%|████      | 109/272 [00:55<01:21,  1.99it/s]

Batches:  40%|████      | 110/272 [00:56<01:21,  1.99it/s]

Batches:  41%|████      | 111/272 [00:56<01:21,  1.98it/s]

Batches:  41%|████      | 112/272 [00:57<01:20,  1.98it/s]

Batches:  42%|████▏     | 113/272 [00:57<01:20,  1.98it/s]

Batches:  42%|████▏     | 114/272 [00:58<01:19,  1.98it/s]

Batches:  42%|████▏     | 115/272 [00:58<01:19,  1.98it/s]

Batches:  43%|████▎     | 116/272 [00:59<01:18,  1.98it/s]

Batches:  43%|████▎     | 117/272 [00:59<01:18,  1.98it/s]

Batches:  43%|████▎     | 118/272 [01:00<01:18,  1.95it/s]

Batches:  44%|████▍     | 119/272 [01:00<01:20,  1.91it/s]

Batches:  44%|████▍     | 120/272 [01:01<01:18,  1.93it/s]

Batches:  44%|████▍     | 121/272 [01:01<01:17,  1.95it/s]

Batches:  45%|████▍     | 122/272 [01:02<01:17,  1.94it/s]

Batches:  45%|████▌     | 123/272 [01:02<01:16,  1.95it/s]

Batches:  46%|████▌     | 124/272 [01:03<01:16,  1.95it/s]

Batches:  46%|████▌     | 125/272 [01:03<01:16,  1.92it/s]

Batches:  46%|████▋     | 126/272 [01:04<01:16,  1.91it/s]

Batches:  47%|████▋     | 127/272 [01:04<01:16,  1.88it/s]

Batches:  47%|████▋     | 128/272 [01:05<01:15,  1.90it/s]

Batches:  47%|████▋     | 129/272 [01:05<01:14,  1.92it/s]

Batches:  48%|████▊     | 130/272 [01:06<01:13,  1.94it/s]

Batches:  48%|████▊     | 131/272 [01:06<01:12,  1.94it/s]

Batches:  49%|████▊     | 132/272 [01:07<01:12,  1.94it/s]

Batches:  49%|████▉     | 133/272 [01:07<01:11,  1.93it/s]

Batches:  49%|████▉     | 134/272 [01:08<01:11,  1.92it/s]

Batches:  50%|████▉     | 135/272 [01:09<01:12,  1.89it/s]

Batches:  50%|█████     | 136/272 [01:09<01:11,  1.90it/s]

Batches:  50%|█████     | 137/272 [01:10<01:11,  1.89it/s]

Batches:  51%|█████     | 138/272 [01:10<01:10,  1.91it/s]

Batches:  51%|█████     | 139/272 [01:11<01:14,  1.78it/s]

Batches:  51%|█████▏    | 140/272 [01:11<01:15,  1.75it/s]

Batches:  52%|█████▏    | 141/272 [01:12<01:12,  1.81it/s]

Batches:  52%|█████▏    | 142/272 [01:12<01:10,  1.85it/s]

Batches:  53%|█████▎    | 143/272 [01:13<01:09,  1.87it/s]

Batches:  53%|█████▎    | 144/272 [01:13<01:07,  1.90it/s]

Batches:  53%|█████▎    | 145/272 [01:14<01:06,  1.92it/s]

Batches:  54%|█████▎    | 146/272 [01:14<01:05,  1.93it/s]

Batches:  54%|█████▍    | 147/272 [01:15<01:05,  1.91it/s]

Batches:  54%|█████▍    | 148/272 [01:15<01:04,  1.92it/s]

Batches:  55%|█████▍    | 149/272 [01:16<01:03,  1.92it/s]

Batches:  55%|█████▌    | 150/272 [01:17<01:04,  1.89it/s]

Batches:  56%|█████▌    | 151/272 [01:17<01:06,  1.81it/s]

Batches:  56%|█████▌    | 152/272 [01:18<01:09,  1.73it/s]

Batches:  56%|█████▋    | 153/272 [01:18<01:08,  1.74it/s]

Batches:  57%|█████▋    | 154/272 [01:19<01:05,  1.80it/s]

Batches:  57%|█████▋    | 155/272 [01:19<01:04,  1.81it/s]

Batches:  57%|█████▋    | 156/272 [01:20<01:04,  1.81it/s]

Batches:  58%|█████▊    | 157/272 [01:21<01:06,  1.73it/s]

Batches:  58%|█████▊    | 158/272 [01:21<01:13,  1.55it/s]

Batches:  58%|█████▊    | 159/272 [01:22<01:09,  1.64it/s]

Batches:  59%|█████▉    | 160/272 [01:22<01:05,  1.70it/s]

Batches:  59%|█████▉    | 161/272 [01:23<01:03,  1.75it/s]

Batches:  60%|█████▉    | 162/272 [01:23<01:00,  1.81it/s]

Batches:  60%|█████▉    | 163/272 [01:24<00:58,  1.87it/s]

Batches:  60%|██████    | 164/272 [01:24<00:57,  1.88it/s]

Batches:  61%|██████    | 165/272 [01:25<00:56,  1.91it/s]

Batches:  61%|██████    | 166/272 [01:26<00:55,  1.93it/s]

Batches:  61%|██████▏   | 167/272 [01:26<00:54,  1.93it/s]

Batches:  62%|██████▏   | 168/272 [01:27<00:54,  1.91it/s]

Batches:  62%|██████▏   | 169/272 [01:27<00:53,  1.91it/s]

Batches:  62%|██████▎   | 170/272 [01:28<00:53,  1.90it/s]

Batches:  63%|██████▎   | 171/272 [01:28<00:52,  1.91it/s]

Batches:  63%|██████▎   | 172/272 [01:29<00:52,  1.90it/s]

Batches:  64%|██████▎   | 173/272 [01:29<00:54,  1.82it/s]

Batches:  64%|██████▍   | 174/272 [01:30<00:52,  1.86it/s]

Batches:  64%|██████▍   | 175/272 [01:30<00:51,  1.89it/s]

Batches:  65%|██████▍   | 176/272 [01:31<00:50,  1.89it/s]

Batches:  65%|██████▌   | 177/272 [01:31<00:51,  1.86it/s]

Batches:  65%|██████▌   | 178/272 [01:32<00:50,  1.87it/s]

Batches:  66%|██████▌   | 179/272 [01:32<00:48,  1.90it/s]

Batches:  66%|██████▌   | 180/272 [01:33<00:48,  1.91it/s]

Batches:  67%|██████▋   | 181/272 [01:33<00:46,  1.96it/s]

Batches:  67%|██████▋   | 182/272 [01:34<00:46,  1.94it/s]

Batches:  67%|██████▋   | 183/272 [01:34<00:46,  1.92it/s]

Batches:  68%|██████▊   | 184/272 [01:35<00:45,  1.93it/s]

Batches:  68%|██████▊   | 185/272 [01:36<00:45,  1.92it/s]

Batches:  68%|██████▊   | 186/272 [01:36<00:44,  1.93it/s]

Batches:  69%|██████▉   | 187/272 [01:37<00:43,  1.94it/s]

Batches:  69%|██████▉   | 188/272 [01:37<00:43,  1.93it/s]

Batches:  69%|██████▉   | 189/272 [01:38<00:42,  1.95it/s]

Batches:  70%|██████▉   | 190/272 [01:38<00:42,  1.95it/s]

Batches:  70%|███████   | 191/272 [01:39<00:41,  1.95it/s]

Batches:  71%|███████   | 192/272 [01:39<00:41,  1.92it/s]

Batches:  71%|███████   | 193/272 [01:40<00:41,  1.91it/s]

Batches:  71%|███████▏  | 194/272 [01:40<00:40,  1.92it/s]

Batches:  72%|███████▏  | 195/272 [01:41<00:40,  1.92it/s]

Batches:  72%|███████▏  | 196/272 [01:41<00:39,  1.91it/s]

Batches:  72%|███████▏  | 197/272 [01:42<00:39,  1.92it/s]

Batches:  73%|███████▎  | 198/272 [01:42<00:40,  1.85it/s]

Batches:  73%|███████▎  | 199/272 [01:43<00:39,  1.85it/s]

Batches:  74%|███████▎  | 200/272 [01:43<00:38,  1.89it/s]

Batches:  74%|███████▍  | 201/272 [01:44<00:37,  1.92it/s]

Batches:  74%|███████▍  | 202/272 [01:44<00:36,  1.94it/s]

Batches:  75%|███████▍  | 203/272 [01:45<00:35,  1.97it/s]

Batches:  75%|███████▌  | 204/272 [01:45<00:34,  1.97it/s]

Batches:  75%|███████▌  | 205/272 [01:46<00:33,  2.00it/s]

Batches:  76%|███████▌  | 206/272 [01:46<00:32,  2.01it/s]

Batches:  76%|███████▌  | 207/272 [01:47<00:32,  2.01it/s]

Batches:  76%|███████▋  | 208/272 [01:47<00:31,  2.03it/s]

Batches:  77%|███████▋  | 209/272 [01:48<00:30,  2.04it/s]

Batches:  77%|███████▋  | 210/272 [01:48<00:30,  2.05it/s]

Batches:  78%|███████▊  | 211/272 [01:49<00:30,  2.03it/s]

Batches:  78%|███████▊  | 212/272 [01:49<00:29,  2.02it/s]

Batches:  78%|███████▊  | 213/272 [01:50<00:29,  2.01it/s]

Batches:  79%|███████▊  | 214/272 [01:50<00:29,  2.00it/s]

Batches:  79%|███████▉  | 215/272 [01:51<00:28,  1.98it/s]

Batches:  79%|███████▉  | 216/272 [01:51<00:28,  1.97it/s]

Batches:  80%|███████▉  | 217/272 [01:52<00:27,  1.97it/s]

Batches:  80%|████████  | 218/272 [01:52<00:27,  1.95it/s]

Batches:  81%|████████  | 219/272 [01:53<00:27,  1.91it/s]

Batches:  81%|████████  | 220/272 [01:53<00:26,  1.93it/s]

Batches:  81%|████████▏ | 221/272 [01:54<00:26,  1.95it/s]

Batches:  82%|████████▏ | 222/272 [01:54<00:25,  1.99it/s]

Batches:  82%|████████▏ | 223/272 [01:55<00:24,  1.98it/s]

Batches:  82%|████████▏ | 224/272 [01:55<00:24,  1.99it/s]

Batches:  83%|████████▎ | 225/272 [01:56<00:23,  1.99it/s]

Batches:  83%|████████▎ | 226/272 [01:56<00:22,  2.01it/s]

Batches:  83%|████████▎ | 227/272 [01:57<00:22,  1.99it/s]

Batches:  84%|████████▍ | 228/272 [01:57<00:21,  2.02it/s]

Batches:  84%|████████▍ | 229/272 [01:58<00:21,  2.00it/s]

Batches:  85%|████████▍ | 230/272 [01:58<00:20,  2.00it/s]

Batches:  85%|████████▍ | 231/272 [01:59<00:20,  2.00it/s]

Batches:  85%|████████▌ | 232/272 [01:59<00:19,  2.03it/s]

Batches:  86%|████████▌ | 233/272 [02:00<00:19,  2.03it/s]

Batches:  86%|████████▌ | 234/272 [02:00<00:18,  2.05it/s]

Batches:  86%|████████▋ | 235/272 [02:01<00:18,  2.04it/s]

Batches:  87%|████████▋ | 236/272 [02:01<00:17,  2.05it/s]

Batches:  87%|████████▋ | 237/272 [02:02<00:17,  2.06it/s]

Batches:  88%|████████▊ | 238/272 [02:02<00:16,  2.04it/s]

Batches:  88%|████████▊ | 239/272 [02:03<00:16,  2.04it/s]

Batches:  88%|████████▊ | 240/272 [02:03<00:16,  1.96it/s]

Batches:  89%|████████▊ | 241/272 [02:04<00:15,  1.98it/s]

Batches:  89%|████████▉ | 242/272 [02:04<00:15,  1.95it/s]

Batches:  89%|████████▉ | 243/272 [02:05<00:14,  1.96it/s]

Batches:  90%|████████▉ | 244/272 [02:05<00:13,  2.01it/s]

Batches:  90%|█████████ | 245/272 [02:06<00:13,  2.06it/s]

Batches:  90%|█████████ | 246/272 [02:06<00:12,  2.04it/s]

Batches:  91%|█████████ | 247/272 [02:07<00:12,  2.01it/s]

Batches:  91%|█████████ | 248/272 [02:07<00:12,  2.00it/s]

Batches:  92%|█████████▏| 249/272 [02:08<00:11,  2.00it/s]

Batches:  92%|█████████▏| 250/272 [02:08<00:10,  2.08it/s]

Batches:  92%|█████████▏| 251/272 [02:09<00:10,  2.06it/s]

Batches:  93%|█████████▎| 252/272 [02:09<00:09,  2.04it/s]

Batches:  93%|█████████▎| 253/272 [02:10<00:09,  2.03it/s]

Batches:  93%|█████████▎| 254/272 [02:10<00:08,  2.09it/s]

Batches:  94%|█████████▍| 255/272 [02:11<00:08,  2.06it/s]

Batches:  94%|█████████▍| 256/272 [02:11<00:07,  2.06it/s]

Batches:  94%|█████████▍| 257/272 [02:12<00:07,  2.11it/s]

Batches:  95%|█████████▍| 258/272 [02:12<00:06,  2.06it/s]

Batches:  95%|█████████▌| 259/272 [02:13<00:06,  2.11it/s]

Batches:  96%|█████████▌| 260/272 [02:13<00:05,  2.08it/s]

Batches:  96%|█████████▌| 261/272 [02:14<00:05,  2.13it/s]

Batches:  96%|█████████▋| 262/272 [02:14<00:04,  2.08it/s]

Batches:  97%|█████████▋| 263/272 [02:14<00:04,  2.10it/s]

Batches:  97%|█████████▋| 264/272 [02:15<00:03,  2.19it/s]

Batches:  97%|█████████▋| 265/272 [02:15<00:03,  2.18it/s]

Batches:  98%|█████████▊| 266/272 [02:16<00:02,  2.15it/s]

Batches:  98%|█████████▊| 267/272 [02:16<00:02,  2.06it/s]

Batches:  99%|█████████▊| 268/272 [02:17<00:01,  2.26it/s]

Batches:  99%|█████████▉| 269/272 [02:17<00:01,  2.15it/s]

Batches:  99%|█████████▉| 270/272 [02:18<00:00,  2.38it/s]

Batches: 100%|█████████▉| 271/272 [02:18<00:00,  2.26it/s]

Batches: 100%|██████████| 272/272 [02:18<00:00,  1.96it/s]

Module embeddings shape: (115, 384)
Degree embeddings shape: (5, 384)
Job embeddings shape: (17346, 384)
Similarity matrix shape: (5, 17346)

In [3]:
for degree_id in ['cs', 'dsa']:
    if (degree_profiles['degree_id'] == degree_id).any():
        print(f'Top-10 jobs for {degree_id}:')
        display(top_k_jobs_for_degree(sim_matrix, degree_profiles, jobs, degree_id, 'sim_score', k=10))

plot_similarity_distributions(sim_matrix, degree_profiles, paths.similarity_distribution_png)
print(f'Saved similarity distribution figure to: {paths.similarity_distribution_png}')

Top-10 jobs for cs:

,rank,job_id,job_title,company,categories,sim_score
0,1,MCF-2025-1715506,Software Development Engineer,NUTEK PRIVATE LIMITED,"Engineering, Manufacturing",0.4751
1,2,MCF-2025-1801982,Software Engineer (Precision / Automation),WECRUIT PTE. LTD.,"Engineering, Information Technology, Manufactu...",0.4723
2,3,MCF-2025-1801975,Software Engineer (Semiconductor Industry),WECRUIT PTE. LTD.,"Engineering, Information Technology, Manufactu...",0.4700
3,4,MCF-2026-0190683,Software Application Engineer - WCAN,WECRUIT PTE. LTD.,Information Technology,0.4629
4,5,MCF-2026-0188112,"Software Senior /Engineer (C#,PLC)- Automated ...",PEOPLE PROFILERS PTE. LTD.,"Engineering, Sciences / Laboratory / R&D",0.4602
5,6,MCF-2026-0189542,Software Developer,ALFA CONNECTIONS PTE. LTD.,Information Technology,0.4502
6,7,MCF-2026-0170526,"Software Engineer (C++/C#, Machine Automation)...",ANRADUS PTE. LTD.,"Information Technology, Others",0.4487
7,8,MCF-2026-0159945,Junior Software Engineer,ALPHA X TECHNOLOGY PTE. LTD.,"Engineering, Information Technology, Manufactu...",0.4460
8,9,MCF-2026-0167383,Applications Developer (Cards Technology),A-IT SOFTWARE SERVICES PTE LTD,"Banking and Finance, Information Technology",0.4456
9,10,MCF-2026-0190672,System Application Engineer - WCAN,WECRUIT PTE. LTD.,Information Technology,0.4452

Top-10 jobs for dsa:

,rank,job_id,job_title,company,categories,sim_score
0,1,MCF-2025-1604902,Data Analyst,MSI GLOBAL PRIVATE LIMITED,"Engineering, Information Technology, Others",0.5470
1,2,MCF-2026-0186942,Principal Data Scientist (Aerospace),RN CARE PTE. LTD.,"Engineering, Information Technology, Manufactu...",0.5441
2,3,MCF-2025-1424769,Data Engineer,DEEGIT ASIA PTE. LTD.,Information Technology,0.5233
3,4,MCF-2025-1164543,Outreach Data Analyst,PERSOL SINGAPORE PTE. LTD.,Public / Civil Service,0.5174
4,5,MCF-2026-0161241,Senior Data Analyst (Bank | Up to 9.5k),ADECCO PERSONNEL PTE LTD,Banking and Finance,0.5087
5,6,MCF-2025-1869712,Data Analyst Lead,INNOVATIQ TECHNOLOGIES PTE. LTD.,"Information Technology, Sciences / Laboratory ...",0.5069
6,7,MCF-2026-0176414,Data Engineer / Data Analyst,L&M FOUNDATION SPECIALIST PTE LTD,Building and Construction,0.5069
7,8,MCF-2026-0183284,Data Analyst,IOTALENTS PTE. LTD.,Information Technology,0.5024
8,9,MCF-2026-0160469,Data Analyst,APAR TECHNOLOGIES PTE. LTD.,Information Technology,0.5020
9,10,MCF-2026-0175746,Data Scientist,QUANTEAM (SINGAPORE) PTE. LTD.,Consulting,0.4999

Saved similarity distribution figure to: /Users/marcusyeo/Github/DSA4264-Text-Group-3/data/figures/similarity_distributions.png